### ISSUE TITLE
find-symbol searches all clj files in project, not just source files

### ISSUE THREAD

**Issue by gfredericks** [clojure-emacs/refactor-nrepl#167] opened 2016-07-29 19:29 UTC
## Expected behavior

Only source files on the classpath should be analyzed
## Actual behavior

All `.clj` and `.cljc` files are analyzed whether or not they are source code; I also have a second checkout of my project in a `git worktree` directory and it analyzes all of those files as well.
## Steps to reproduce the problem

```
# in the root of the project
echo "#foo bar" > baz.clj
```

Try to do a replace-symbol refactoring.

A `No reader function for tag foo` error is reported.
### clj-refactor.el and refactor-nrepl version information

clj-refactor 2.2.0
### CIDER version information

```
;; CIDER 0.12.0 (Seattle), nREPL 0.2.12
;; Clojure 1.8.0, Java 1.7.0_80
```
### Leiningen or Boot version

Leiningen 2.6.1 on Java 1.7.0_80 Java HotSpot(TM) 64-Bit Server VM
### Emacs version

24.5.1
### Operating system

Ubuntu 14.04

**Comment by expez** [comment] 2016-07-30 11:10
I don't know what you mean by a second checkout in a `git worktree`, but if the folders with the files you want excluded reside below a directory on the classpath then we're going to analyze them.

If you have some suggestions as to how we can distinguish source files we should analyze from source files we should skip, other than whether they are on the cp or not, I'm open to suggestions.

**Comment by gfredericks** [comment] 2016-07-30 12:48
No I'm not talking about files on the classpath -- the current behavior is that all files reachable from the project root are analyzed, classpath or not. The specific example I gave is a file at the root of the project.

I suppose I should distinguish between "analyzing" and "reading", because my most specific problem is that all of the files are read, which causes the `no reader function` error.

**Comment by expez** [comment] 2016-07-30 13:41
Thanks @gfredericks.  This is definitely a bug.  

@benedekfazekas The problem is the fallback dir used [here](https://github.com/clojure-emacs/refactor-nrepl/blob/master/src/refactor_nrepl/find/find_symbol.clj#L133), which is the project root.

**Comment by gfredericks** [comment] 2016-07-30 13:53
When I was doing my own debugging I *thought* I saw that that was set earlier actually, perhaps in emacs. My temporary workaround was to monkeypatch `find-symbol` so that it adds `/src` and `/test` to the `:dir` option passed in, so I'm 96% sure it's set elsewhere.

**Comment by gfredericks** [comment] 2016-07-30 13:54
So arguably this could be a bug in `clj-refactor`, but my guess is that `clj-refactor` needs `refactor-nrepl`'s help to determine the proper directories to look in anyhow.

**Comment by expez** [comment] 2016-07-30 14:05
Yeah, it might be set earlier but `clj-refactor` doesn't know shit, so if it's sending anything down it's the project root :/

**Comment by narendraj9** [comment] 2017-04-01 22:57
Is there any reason find-symbol isn't looking only in the dependent namespaces for a symbol? @expez

**Comment by expez** [comment] 2017-04-02 07:45
> Is there any reason find-symbol isn't looking only in the dependent namespaces for a symbol? @expez

You can use a symbol without requiring it in the ns form, so without analyzing it is hard find all occurrences.

**Comment by narendraj9** [comment] 2017-04-02 09:16
@expez Can you give me an example where I can do so? I cannot think of any.

**Comment by expez** [comment] 2017-04-02 10:07
`(resolve 'some.ns/some-fn)` gives you `some-fn` which you can then call.  You'll sometimes see people do this because of problems with circular dependencies, that they don't have time or will to resolve properly.

You can also just put a `(require 'some.ns`) anywhere in the file, instead of in the ns-form, and then use `some-fn`.  This might happen e.g. in a macro to conditionally include something.

I'll grant you that these are edge-cases, and we had other reasons for doing it this way too, back in the day.  It was easier, and we didn't yet have the code in place to statically determine namespace dependencies.

**Comment by narendraj9** [comment] 2017-04-02 10:21
@expez At work, we have a huge project with hundreds or maybe thousands of files. A lot of those files are migrators. While working on the project, I am most of the times trying to understand a piece of code by looking at how something has been used elsewhere. Since we look at all the files in no particular order, it takes a huge amount of time to find usages for the symbol. 

I was thinking if I should just change this to look in the dependents with `tracker/get-dependents` and including the file of the namespace to the list returned by `get-dependents`. 

For some of the namespaces in the project, the AST generation fails. So, I set ignore errors in `clj-refactor`. Even though I get ast stats telling me that it failed. I am hoping that we still have ASTs for the rest of the name spaces. 

Isn't AST generation independently done for files? I understand we need to have all macros that we depend upon expanded so the file containing the macro needs to be evaluated before building AST for a file containing the AST. So, would the failed namespaces affect other namespaces if they define macros used by other namespaces?

**Comment by expez** [comment] 2017-04-02 10:44
If most of the files are migrators, it sounds like the first thing we should do is solve this issue, or find another way to exclude those files.

The next step would probably be to add some parallelism.  There is some already, but we could probably benefit from more.  If that doesn't get us there, then we should probably resign ourselves to only handling the 99% case, as these edge-cases are clearly very rare.

**Comment by narendraj9** [comment] 2017-04-02 13:26
@expez So generating AST for namespaces can be done in parallel for all namespaces? Then I think we can just change to using `pmap` instead of map on the files while we are warming the AST.

**Comment by benedekfazekas** [comment] 2017-05-08 09:03
nrepl middleware backend now accepts/understands configuration to ignore specific paths. no integration with it in `clj-refactor.el` yet

**Comment by narendraj9** [comment] 2017-10-14 19:29
This commit parallelizes AST building: https://github.com/narendraj9/refactor-nrepl/commit/1b2a05885126e0ebe4d476ef5f97d0d968fbcdef  

@expez   Please review if it can be merged.

**Comment by expez** [comment] 2017-10-15 10:16
@narendraj9 Thanks for investigating!

Just go ahead and open a PR and we'll take the discussion there.

**Comment by MalloZup** [comment] 2019-08-05 21:39
autogenerated with https://github.com/MalloZup/doghub:  issue inactive since 450 days. Please update the issue or close it

**Comment by expez** [comment] 2021-06-28 11:53
Closing this because we have the ability to ignore paths now, and it's been exposed in clj-refactor.

**Closed by expez** 2021-06-28 11:53 UTC
Labels: bug
