### ISSUE TITLE
find-symbol throws exception when using lein profiles 

### ISSUE THREAD

**Issue by rundis** [clojure-emacs/refactor-nrepl#32] opened 2015-03-05 07:41 UTC
I have a project with a profiles section containing:
```clojure
:profiles {:dev {:plugins [[lein-ring "0.8.13"]
                             [drift "1.5.2"]]
                   :source-paths ["dev"]
                   :test-paths ^:replace []}
             :test {:dependencies [[midje "1.6.3"]]
                    :plugins [[lein-midje "3.1.3"]]
                    :test-paths ["test"]
                    :resource-paths ["test/resources"]}}
```

* I connect to the project (through Light Table btw) without specifying a profile, ie test sources are not part of my classpath.
* When I try to invoke find-symbol it returns a result, but eventually it will also throw/print an exception like below

Might be a user error from my side, but I would have thought that since test namepaces aren't part of my classpath they shouldn't be analyzed either ?

```clojure
[clojure-agent-send-off-pool-92] ERROR clojure.tools.nrepl.server - Unhandled REPL handler exception processing message {:id d94991e8-087b-4aa4-a99d-2bf90f439fd1, :name check-produsent, :ns helsegris-api.produsent.domain, :op refactor, :refactor-fn find-symbol}
java.lang.AssertionError: Assert failed: Can't find helsegris-api.core-test in classpath
res
	at deps.toolsanalyzerjvm.v0v6v5.clojure.tools.analyzer.jvm$analyze_ns.invoke(jvm.clj:535)
	at deps.toolsanalyzerjvm.v0v6v5.clojure.tools.analyzer.jvm$analyze_ns.invoke(jvm.clj:531)
	at deps.toolsanalyzerjvm.v0v6v5.clojure.tools.analyzer.jvm$analyze_ns.invoke(jvm.clj:530)
	at refactor_nrepl.analyzer$build_ast.invoke(analyzer.clj:52)
	at refactor_nrepl.analyzer$cachable_ast.invoke(analyzer.clj:59)
	at refactor_nrepl.analyzer$ns_ast.invoke(analyzer.clj:65)
	at refactor_nrepl.refactor$find_symbol_in_file.invoke(refactor.clj:97)
	at clojure.lang.AFn.applyToHelper(AFn.java:156)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invoke(core.clj:626)
	at clojure.core$partial$fn__4228.doInvoke(core.clj:2468)
	at clojure.lang.RestFn.invoke(RestFn.java:408)
	at clojure.core$map$fn__4245.invoke(core.clj:2559)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:598)
	at clojure.core$next.invoke(core.clj:64)
	at clojure.core$concat$cat__3957$fn__3958.invoke(core.clj:701)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:56)
	at clojure.lang.RT.seq(RT.java:484)
	at clojure.core$seq.invoke(core.clj:133)
	at clojure.core$map$fn__4245.invoke(core.clj:2551)
	at clojure.lang.LazySeq.sval(LazySeq.java:40)
	at clojure.lang.LazySeq.seq(LazySeq.java:49)
	at clojure.lang.Cons.next(Cons.java:39)
	at clojure.lang.RT.next(RT.java:598)
	at clojure.core$next.invoke(core.clj:64)
	at refactor_nrepl.refactor$find_symbol_reply.invoke(refactor.clj:145)
	at refactor_nrepl.refactor$wrap_refactor$fn__10247.invoke(refactor.clj:190)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__431.invoke(middleware.clj:17)
	at cider.nrepl.middleware.apropos$wrap_apropos$fn__14222.invoke(apropos.clj:102)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__431.invoke(middleware.clj:17)
	at refactor_nrepl.find_unbound$wrap_find_unbound$fn__13560.invoke(find_unbound.clj:24)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__431.invoke(middleware.clj:17)
	at cider.nrepl.middleware.classpath$wrap_classpath$fn__14249.invoke(classpath.clj:25)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__431.invoke(middleware.clj:17)
	at refactor_nrepl.artifacts$wrap_artifacts$fn__14184.invoke(artifacts.clj:126)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__431.invoke(middleware.clj:17)
	at clojure.tools.nrepl.server$handle_STAR_.invoke(server.clj:18)
	at clojure.tools.nrepl.server$handle$fn__787.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__4145.invoke(core.clj:1910)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by benedekfazekas** [comment] 2015-03-05 08:08
hm...I think the problem is that refactor-nrepl finds the source file for `core-test` but it is not on the classpath therefore can not be analyzed, no AST can be built. a workaround could be that you tell find symbol in which subdirectory should it look. `src` would be my guess for this case.

hope this helps

**Comment by expez** [comment] 2015-03-05 08:55
We should filter the list of files against files on the classpath, @benedekfazekas.  This seems like a bug to me.

**Comment by benedekfazekas** [comment] 2015-03-05 08:57
well, @rundis says above find-symbol actually returns successfully. so I would say the only problem here is that the above exception seems to be an **ERROR**. it is rather a **WARn** really

**Comment by rundis** [comment] 2015-03-05 09:00
Ah ! 
right so a workaround for now could be to specify the  ```clj-dir``` key ?  
[this](https://github.com/clojure-emacs/refactor-nrepl/blob/a40b1631fa5bb95d0429555679d110a43bbcee4e/src/refactor_nrepl/refactor.clj#L104) suggests the classpath is not used when analyzing clj files ?

**Comment by benedekfazekas** [comment] 2015-03-05 09:05
`clj-dir`: yup

that is perhaps a bit misleading. ns/namespace here is the namespace of the symbol you are searching for *not* the namespace of a given source ns you are searching in. see [this line](https://github.com/clojure-emacs/refactor-nrepl/blob/a40b1631fa5bb95d0429555679d110a43bbcee4e/src/refactor_nrepl/refactor.clj#L111) and then [this](https://github.com/clojure-emacs/refactor-nrepl/blob/a40b1631fa5bb95d0429555679d110a43bbcee4e/src/refactor_nrepl/refactor.clj#L96)

**Comment by expez** [comment] 2015-03-05 09:13
@benedekfazekas i recently changed `ns-ast` to error out instead of silently continuing.  I did this because I want `clean-ns` to fail instead of emptying the ns form of all dependencies when it can't build an AST to work on.  Furthermore, I think the semantics of the other operations are such that failure also makes sense instead of doing say a partial renaming project wide.

The exception here is `find-usages` where the results are streamed back as they are found, but I think this is an OK compromise.

I think we have to do some work to ensure we only act on files that are present on the classpath.

**Comment by benedekfazekas** [comment] 2015-03-05 09:18
missed this one. will look into this some time soon

**Comment by expez** [comment] 2015-03-07 17:04
I'll close this one and open another issue with work being done of files not present on classpath

**Closed by expez** 2015-03-07 17:04 UTC
Labels: bug

**Comment by benedekfazekas** [comment] 2015-03-08 16:16
on clojars. workaround with `clj-dir` is not necessary anymore

**Comment by rundis** [comment] 2015-03-08 18:45
Sweet! Works a charm.

**Comment by expez** [comment] 2015-03-08 19:32
@rundis I just saw the demo you published showcasing the LT plugin.  Really impressive how much you've accomplished in such a short amount of time. Also, it's quite satisfying to see `refactor-nrepl` put to such good use :+1:

**Comment by benedekfazekas** [comment] 2015-03-08 19:37
just watched too. :+1:

**Comment by rundis** [comment] 2015-03-08 19:53
Cheers guys ! 
Feels like you have done the hard parts and I'm mostly harvesting from your excellent efforts :)
Keep up the good work. 

Btw I nicked your pprint-ns and clojurescriptified it [here](https://github.com/rundis/clj-light-refactor/blob/master/src/lt/plugins/cljrefactor/pprint.cljs). I'm no license wizard, so how should I go about credit your project (of if it's not kosher I'll remove it) ?

**Comment by expez** [comment] 2015-03-08 20:19
Why did you have to nick it?  Can't you use the pprinted string returned by the middleware?

Don't worry about the license.  You've mentioned the `refactor-nrepl` in the `README` and that's appreciated.

**Comment by rundis** [comment] 2015-03-08 20:45
I might have convoluted things, but I can't see a clear path to not having it on the client side. 
When I do resolve missing I wish to add/mod the ns, that needs to happen on the client (he/she might even be prompted to make a selection). 

Anyways you guys are gonna need an irc or mailing list eventually. This discussion is way off topic :)

**Comment by bbatsov** [comment] 2015-03-08 22:37
#clojure-emacs

**Comment by rundis** [comment] 2015-03-08 22:41
Ah cool. Tx.

**Comment by expez** [comment] 2015-03-09 07:02
@rundis right now we just insert the selected libspec into the ns form, without worrying about how pretty the result is and then run `clean-ns` afterwards.  I haven't turned on `auto-clean-ns` yet, but it might be time to do that.  Most of the kinks in `clean-ns` and the associated pretty-printing code has been ironed out and the op now fails gracefully when it can't do things thing (e.g. if it's unable to build an AST).

I had no idea how hard proper pretty-printing was, even when the scope is so limited. The current pprinting code grew like a cancerous mass from a few lines of hacks on top of pprint into the current atrocity in a frightening speed.  Eventually all the code will be dropped in favor of delegating to [cljfmt](https://github.com/weavejester/cljfmt). `cider-nrepl` already has support for `cljfmt` so that won't create much work for any of us.
