### ISSUE TITLE
replace mranderson with a better solution to avoid dependency clashes between refactor-nrepl and the project being refactored

### ISSUE THREAD

**Issue by benedekfazekas** [clojure-emacs/refactor-nrepl#20] opened 2015-01-26 17:53 UTC
two candidates so far:
- [pods](https://github.com/boot-clj/boot/wiki/Pods)
- [lein-capsule](https://github.com/circlespainter/lein-capsule) and [capsule](https://github.com/puniverse/capsule)

both of them seem to do a proper classloader level isolation for dependencies (this is a very generic statement) while mranderson simply munges ns declarations

**Comment by expez** [comment] 2015-01-30 13:35
@circlespainter I've been trying to package up this project and the capsule seems to be generated OK with just

```clj
  :capsule {:types {:fat {}}}
```

but `lein` isn't picking up the middleware.  I've also tried with 

```clj
  :capsule {:main refactor-nrepl.plugin/middleware
            :aot [refactor-nrepl.plugin]
            :types {:fat {}}}
```

but that didn't help.  Any ideas?

Do you think `capsule` is a good fit for packaging up a project like this, or is it mostly targeted at standalone applications?

**Comment by benedekfazekas** [comment] 2015-01-30 13:41
[boot] pls see the `boot` branch for a kinda working boot build. I tried to podize pomegranate usage in `artifacts` namespace and only half success: I can not create a jar with boot which works in a non boot environment. when I start up repl in a test project with lein I get:
```
sample-webapp.core=> Exception in thread "Thread-3" java.lang.NullPointerException
	at boot.App.newPod(App.java:161)
	at boot.pod$make_pod.invoke(pod.clj:347)
	at boot.pod$pod_pool$fn__1078.invoke(pod.clj:389)
	at boot.pod$lifecycle_pool$fill__1051.invoke(pod.clj:317)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.lang.Thread.run(Thread.java:722)
```

my hunch is that the pod environment does not get bootstrapped outside boot... no idea if I am doing the whole thing right tbh. any ideas anybody?

**Comment by circlespainter** [comment] 2015-01-30 13:54
@expez I'm not sure I understand completely your use case but but Capsule is meant as a dead-easy deployment package for standalone JVM applications. The project's (or `lein-capsule`'s declared) main is what will get run when you execute the capsule on the command line and you can verify it being picked up correctly by looking at the capsule's manifest.

In your `project.clj` I don't see any main namespace being declared, which is consistent with my understanding that your project (sorry, not yet familiar with it) is being used as a Leiningen plugin, not as a standalone application.

So is it Leiningen not picking up your capsule? AFAIK Leiningen picks up plugins through namespace naming conventions and not by executing a standalone JAR in a separate JVM process (but maybe it can do that as well and I'm just unaware?), so this could be the reason why it's not working.

**Comment by expez** [comment] 2015-01-30 14:19
@circlespainter the use case here is that `refactor-nrepl` provides tooling for working with clj projects.  The problem we're having now is that `refactor-nrepl` is growing and some of its dependencies are interfering with the the dependencies of the project the user is working on, because everything is loaded into the same classloader.  What we'd like to do is to isolate `refactor-nrepl` to avoid this trouble.  

I think the way forward is to provide a leiningen plugin which talks to the active nrepl server and then have that thin plugin talk to an isolated app, say `refactor-nrepl-core` which runs as a standalone application built using `lein-capsule`.  Does that sound reasonable?

**Comment by circlespainter** [comment] 2015-01-30 14:30
@expez Yes I think it does, or you could package your plugin as an uberjar with your dependencies relocated to other packages (not sure if Leiningen's uberjar can do it, maybe not; other JVM build tools like Gradle have the relocation capability during shadowing through plugins). Maybe it should be possible to use custom classloaders too, not sure how comfy that is in this context though.

**Comment by micha** [comment] 2015-01-30 14:40
@benedekfazekas You're right, pods only really work when created from a Java class loader that is outside of any Clojure runtime. Boot itself is a Java program that creates a number of pods in which Clojure code is evaluated. The entrypoint of boot is this Java class: https://github.com/boot-clj/boot/blob/master/boot/base/src/main/java/boot/App.java.

**Comment by benedekfazekas** [comment] 2015-01-30 14:43
so @micha you are basically saying that if I create pods with the clojure API boot provides in the `boot.pod` namespace then these pods will only work in a boot environment. do I understand you correctly?

**Comment by micha** [comment] 2015-01-30 14:48
@benedekfazekas Unfortunately, that's correct. The `boot.pod/make-pod` function is actually calling the `boot.App/newPod` static method: https://github.com/boot-clj/boot/blob/master/boot/pod/src/boot/pod.clj#L347. This class needs to be initialized via the `boot.App/main` method. Even if you initialize it, I'm not sure it will be able to work. I'm pretty sure that the `App` class needs to be loaded before any Clojure runtimes are.

**Comment by benedekfazekas** [comment] 2015-01-30 14:53
thx @micha for the answers!

@expez at this point I am wondering if we should
- have stab at solving this problem directly with [shimdandy](https://github.com/projectodd/shimdandy)
or
- work or mranderson to be able to inline java source parts of clj libs...

**Comment by expez** [comment] 2015-01-30 17:22
The problem is we need access to the active `nrepl` for quite a bit of stuff.  Off the top of my mind `hotload-dependency` runs code in the currently active repl and we even call `cider-var-info` directly to find out if some var is a macro or not.

@bbatsov what about spinning up the nrepl server, with all middleware, in its own jvm/classloader?  While not ideal, at least we're limited to avoiding dependency conflicts between tools, which seems much more manageable.

**Comment by benedekfazekas** [comment] 2015-01-30 18:05
is not pomegranate a good example tho? all we need to run in a separate classloader (so to say) is the pomegranate calls (see the `boot` branch) the rest does not really matter... or what do i miss here?

**Comment by expez** [comment] 2015-01-30 19:11
well today the problem is pomegranate, but tomorrow it might be something else.  I'd rather fix this once and for all, if possible.

**Comment by benedekfazekas** [comment] 2015-01-30 19:44
we may be saying the same thing actually: what I mean is if we wrap all **dependencies** in 'pods' or something similar: eg they are loaded by a separate classloader then we are good to go.

**Comment by expez** [comment] 2015-01-30 20:00
ya, that would work

**Comment by benedekfazekas** [comment] 2015-01-30 20:04
annoying what we really need is these pods but without boot. I guess I can try to analyze [Appj.ava](https://github.com/boot-clj/boot/blob/master/boot/base/src/main/java/boot/App.java) and see if the pod idea can be factored out from there...

**Comment by expez** [comment] 2015-01-30 20:09
if we put pomegranate in a separate classloader then it won't be able to hotload the dependencies, I think.  It will just load the dependency into that isolated classloader, right?

**Comment by expez** [comment] 2015-01-30 20:12
looking at the code for pomegranate `add-dependencies` doesn't take a classloader as an arg, but we might call `add-classpath` ourselves where one of the arities lets you provide another classloader.

**Comment by benedekfazekas** [comment] 2015-01-30 20:17
actually hotload perhaps not the best example here as the feature needs to mess with the classpath (classloaders) itself. but if we assume that there is a dependency we use to do something: retrieve something from the network, build an ast etc. in theory we can do that in a separate classloader. as long as we can access the result we don't really need to access the stuff there... (not 100% sure actually if that is true... ;) )

**Comment by micha** [comment] 2015-01-31 17:43
@benedekfazekas i think the problem may just be that `App.java` isn't being properly initialized before you call `make-pod`. It has a number of static properties that control how pods are created that are normally populated by `App/main`. If you want to try to refactor it so it will work outside of boot I will merge your changes.

I think one thing you will need to do is load the boot jars into a classloader that is not a child of any Clojure classloader. Then you can access `boot.App` from that classloader and use it to create pods.

**Comment by benedekfazekas** [comment] 2015-01-31 17:55
hm @micha I might give it a try.

**Comment by benedekfazekas** [comment] 2015-02-02 09:55
I played around with this a bit and although my thoughts/findings are a bit halfbaked I want to share early to get some feedback and to see if I am on the right track. first of all @expez was right saying
> if we put pomegranate in a separate classloader then it won't be able to hotload the dependencies, I think. It will just load the dependency into that isolated classloader, right?

so right: we need to explicitly specify the classloader for add-classpath (this fn is duplicated in boot btw).

The problem with that @micha that boot explicitly seals the AppClassLoader in `boot.pod/seal-app-classloader`. Why is that? I've read the explanation linked in the doc there in cider readme: still does not really get it. Perhaps it does not apply to our case? Refactor-nrepl works in a repl basically. (sidenote: I refactored `App.java` very minimally: only created a public init method with most of the code pasted into it from `static main`) I tested the whole thing with a very simple application only depending on clojure 1.6.0, started up the repl with leiningen, if I printed the classloaders with and without a pod I got:
```
(println "cls from app: " (pod/classloader-hierarchy))
(println "cls from pod: " (.invoke pomegranate-pod "cemerick.pomegranate/classloader-hierarchy"))

cls from app:  (#<AppClassLoader sun.misc.Launcher$AppClassLoader@68ffab0a> #<ExtClassLoader sun.misc.Launcher$ExtClassLoader@69365360>)
cls from pod:  (#<URLClassLoader java.net.URLClassLoader@3594fb0e> #<AppClassLoader sun.misc.Launcher$AppClassLoader@68ffab0a> #<ExtClassLoader sun.misc.Launcher$ExtClassLoader@69365360>)
```
So as far as I can see since AppClassLoader is sealed there is no suitable classloader to load the new jar into.

That said I still think that our hotload dependency is not really the best feature to experiment with this as it needs to modify the classpath itself. So for further experimenting with bootless pods I think the best would be to try to apply it to an other dependency of ours.

Hope this makes a bit of sense I know it is messy.

**Comment by expez** [comment] 2015-02-02 10:06
Why go via pods and not just use `shimdandy` directly like I attempted to do?

**Comment by benedekfazekas** [comment] 2015-02-02 11:00
I am not against that. as we are in experimenting phase so to say does not hurt to try both. and @micha did not sound like being against 'bootless' pods in his comments. I do have the hunch that doing our own solution points towards doing our little framework to handle dependencies in separate classloaders tho and pods sound like this already to me... but again: i would be more than happy with a working solution either way...

**Comment by bbatsov** [comment] 2015-02-08 08:49
Let me know if you manage to solve this. There's plenty of functionality that I'd like to add to `cider-nrepl`, but I don't just because I'm afraid of the dep conflicts that this might introduce.

**Comment by expez** [comment] 2015-02-08 09:13
@bbatsov I was linked [this gist](https://gist.github.com/tobias/f2cbb026977299c8c71e) yesterday which loads pomegranate into its own classloader, using only clojure internals.  I haven't had the time to try it out, but you're welcome to take a look :)

**Comment by benedekfazekas** [comment] 2015-02-08 09:43
@micha can you enlighten me why boot explicitly seals the AppClassLoader in `boot.pod/seal-app-classloader`?

**Comment by micha** [comment] 2015-02-08 16:53
@benedekfazekas Sure, that's there to protect boot from libraries that rudely mess around with classloaders they shouldn't be messing with. I spent a lot of time trying to get boot to work with an approach along the lines of [ninjudd/classlojure](https://github.com/ninjudd/classlojure) (similar to the gist above) but was ultimately unsuccessful.

The objective:
* A mechanism for dynamically creating multiple isolated Clojure runtimes whose dependencies do not affect each other in any way.
* An interface that allows any of these isolated runtimes to evaluate expressions in another runtime and retrieve the results, with side effects supported as expected.

The problems:
* Almost everything in Clojure is dynamic. Protocols are especially problematic, because each runtime creates its own unique implementations when core is loaded.
* All of these things are created in the thread context class loader (TCCL).
* Classes, interfaces, etc. are resolved in a somewhat counter-intuitive way: when a class is requested, it is first resolved in the topmost class loader in the hierarchy &mdash; if the class isn't found there then it's resolved in the next child, and so on. This relationship is inverted relative to the scoping rules we normally expect.
* If a class loader is modified, it will override all of its children (per the previous point).
* Anyone can molest any class loader, and nobody really understands class loaders. So it's likely that code will be fishing around in random class loaders visible to it in the hierarchy.
* Since class loader fishing is common, it's crucial to ensure that Clojure code being evaluated doesn't have any class loaders it can harm in its hierarchy, because if they're accessible it's almost guaranteed that someone will do something insane with it.
* If any Clojure interfaces, protocols, etc. leak out into a class loader that is visible from another Clojure runtime, that second runtime will be broken, because it will be resolving things created by the other runtime, and the instances won't match up with other interfaces and classes resolved in its own class loader.

The solution we arrived at with boot &mdash; strict control of the class loader hierarchy:
* Start with a Java executable, to ensure that no class loaders can resolve any Clojure classes or interfaces, period.
* Carefully create new class loaders for the Clojure runtimes, with their class loader hierarchies arranged such that they are all siblings and have no ancestors with access to anything Clojure related.

This last point is the reason for sealing the app class loader: it's visible to all Clojure runtimes so if it's not sealed someone will surely fish around in there and ruin isolation accidentally. (We saw this with nREPL immediately, for example.) It's really hard to debug class loader problems, too.

**Comment by benedekfazekas** [comment] 2015-02-09 08:36
thx @micha for the detailed answer. that basically means that hotload dependency won't work in a poded environment unless we create an other ancestor classloader in between app and pod classloaders: but this would break the principles you quoted.

meanwhile I will still continue to investigate podizing other ("simpler") dependencies as pods can still solve the underlying problem for most of the dependencies.

**Comment by micha** [comment] 2015-02-09 22:26
@benedekfazekas I have a feeling that something like a [post-delegation classloader](http://tech.puredanger.com/2006/11/09/classloader/) might be a possible alternative somehow, but I couldn't really figure out how to apply it to implement pods. Maybe you can make it work :)

**Comment by benedekfazekas** [comment] 2015-02-10 08:20
oi @micha I deffo can **try** ;)

**Comment by benedekfazekas** [comment] 2015-03-07 23:30
[classlojure](https://github.com/ninjudd/classlojure) is also an option

**Comment by expez** [comment] 2015-03-10 19:20
I'm thinking the following approach might work:

Wrapper project `refactor-nrepl` which contains `alembic` and `classlojure` and just enough code to send and receive `nrepl` messages.  This wrapper bootstraps itself by using `alembic` (which uses `pomegranate` in an isolated classloader) to download `refactor-nrepl-core` and all of `core`'s dependencies.  It then creates a new classloader with all the jars that were then downloaded and evals any request from the middleware in that isolated classloader.

**Comment by bbatsov** [comment] 2015-03-12 15:09
You might want to join this discussion https://groups.google.com/forum/#!topic/clojure-dev/Dl3Stw5iRVA

**Comment by benedekfazekas** [comment] 2015-03-12 15:58
i've got there too late. we got booted

**Comment by bbatsov** [comment] 2015-03-12 18:09
Btw, @cemerick started a new thread about the deps isolation.

**Comment by expez** [comment] 2015-04-02 10:48
mranderson now works on java deps too, closing this for now.

**Closed by expez** 2015-04-02 10:48 UTC
Labels: enhancement
