### ISSUE TITLE
tools.namespace's tracker doesn't handle namespaces of same name across dialects

### ISSUE THREAD

**Issue by magnars** [clojure-emacs/refactor-nrepl#127] opened 2015-11-03 16:09 UTC
Here's a new one for me:

```
clojure.lang.ExceptionInfo: Circular dependency between quiescent.core and quiescent.core
 at clojure.core$ex_info.invoke (core.clj:4593)
    mranderson046.toolsnamespace.v0v3v0_alpha1.clojure.tools.namespace.dependency.MapDependencyGraph.depend (dependency.cljc:89)
    mranderson046.toolsnamespace.v0v3v0_alpha1.clojure.tools.namespace.track$add_deps$fn__50653$fn__50655.invoke (track.cljc:26)
```

Full stack: https://gist.github.com/magnars/43702192d9d8108f98eb

The namespace for `quiescent.core` in clj is simply:

```clj
(ns quiescent.core)
```

The namespace for `quiescent.core` in cljs is:

```clj
(ns quiescent.core
  (:require [cljsjs.react])
  (:require-macros [quiescent.core :refer [react-method]]))
```

**Comment by benedekfazekas** [comment] 2015-11-03 16:16
this is basically toolsnamespace 0.3.0-alpha1 complaining I don't think it is mranderson specific. we rather need to poke around the `ns.tracker` I guess:

```
mranderson046.toolsnamespace.v0v3v0_alpha1.clojure.tools.namespace.file$add_files.invoke (file.clj:81)
    refactor_nrepl.ns.tracker$build_tracker.invoke (tracker.clj:11)
    refactor_nrepl.find.find_macros$find_macro.invoke (find_macros.clj:209)
    refactor_nrepl.find.find_symbol$find_symbol$fn__55197.invoke (find_symbol.clj:254)
```

thx for the report @magnars

**Comment by expez** [comment] 2015-11-03 16:43
I'm not sure if this is problem with our usage or an actual bug in the implementation of tools.namespace.  

I'm reading [TNS-35](http://dev.clojure.org/jira/browse/TNS-35) to mean that clojurescript support isn't working correctly yet.  Is that correct, @stuartsierra?

**Comment by stuartsierra** [comment] 2015-11-03 18:01
tools.namespace supports .cljs and .cljc as of 0.3.0-alpha1. [TNS-35](http://dev.clojure.org/jira/browse/TNS-35) should have been closed with that release — I just closed it.

But tools.namespace can't handle the case of two files defining the same namespace. I added [TNS-38](http://dev.clojure.org/jira/browse/TNS-38) to track this issue. This might be difficult to fix in the near-term, since tools.namespace assumes a one-to-one correspondence between namespaces and files.

**Comment by stuartsierra** [comment] 2015-11-06 22:25
Even with a fix for TNS-38, there may be other complications here. 

[refactor-nrepl.ns.tracker](https://github.com/clojure-emacs/refactor-nrepl/blob/fc5f293336258274769275b94425df5475d44afb/src/refactor_nrepl/ns/tracker.clj#L11) uses `clojure.tools.namespace.file/add-files` on all source files regardless of extension: `.clj`, `.cljs`, or `.cljc`.

Since there may be multiple files for the same namespace with different extensions, there is no way to know which one will be stored in `:clojure.tools.namespace.file/filemap`, used in [refactor-nrepl.ns.tracker/project-files-in-topo-order](https://github.com/clojure-emacs/refactor-nrepl/blob/fc5f293336258274769275b94425df5475d44afb/src/refactor_nrepl/ns/tracker.clj#L25).

An even more complicated, though unlikely, scenario: Since refactor-nrepl.ns.tracker merges the dependency graphs of Clojure and ClojureScript sources, it could potentially find cyclic dependencies between Clojure and ClojureScript code which do not exist in either language separately.

Mixed Clojure/ClojureScript projects open up all kinds of complications for tooling. I'm just starting to discover them for tools.namespace; I expect there will be more.

**Comment by expez** [comment] 2015-11-08 12:46
@stuartsierra We use the tracker, among other things, in `rename-file-or-dir` to find the dependent namespaces which need to be updated after a source file is moved.  The only way to get this to work, in the general case, is to put all variants of source files in the tracker.

It would be great if this could be made to work reliably.  For now, I'll limit the scope of the tracker we're building to only `clj` files whenever possible.

**Comment by stuartsierra** [comment] 2015-11-13 15:30
I've fixed [TNS-38](http://dev.clojure.org/jira/browse/TNS-38) which resolves the specific case of `:require-macros` from a `.cljs` file to a `.clj` file. This is included in tools.namespace release 0.3.0-alpha2.

**Comment by benedekfazekas** [comment] 2015-11-13 15:32
@stuartsierra thanks, will give a try to `0.3.0-alpha2`

**Comment by expez** [comment] 2015-11-13 15:41
@stuartsierra we use TNS to find dependent files, e.g. when one file is moved we need to update the ns forms of dependent files to require the right thing and fix up fully-qualified references.  

With this change, we'll now report success to the user, but fail to update one of the affected files when the user performs a rename-file refactoring.  To me this is a regression, as I'd much rather have the op blow up than perform a partial refactoring and report success.

**Comment by benedekfazekas** [comment] 2015-11-13 15:43
I am just about publishing a new snapshot with upgraded tns? @expez do you prefer this to be reverted?

**Comment by expez** [comment] 2015-11-13 15:44
Yes, I think it's better to fail in this edge-case than perform a partial refactoring and tell the user all is OK.

**Comment by stuartsierra** [comment] 2015-11-13 19:50
Well, that's why -alpha releases are useful. :) I will reconsider
[TNS-38] in light of this feedback. Thanks for testing the alphas and
reporting.

This discussion is leading me to think that [deps-from-ns-decl] should
ignore `:require-macros` completely, because it crosses the “platform”
boundary between ClojureScript and Clojure. That would be a different
way of resolving [TNS-38] from the solution in -alpha2, but it still
wouldn’t help for this use case.

Regardless of how tools.namespace ends up handling `:require-macros`,
it probably won’t be able to provide the perfect answer for the use
cases here, because it only tracks dependencies among namespaces, not
among files. tools.namespace has no way to represent a dependency
between two files which both declare the same namespace.

[add-files] on two different files with the same namespace is
undefined. Even detecting that as an error would require adding more
state to the tracker, which is already too complicated.

It might be possible to deal with this problem using separate trackers
for Clojure and ClojureScript, but I haven’t tested that scenario.
Even then, there’s still no way to accurately represent the fact that
`foo.cljs` depends on `foo.clj`.

I have some vague ideas for a redesigned tools.namespace which might
be able to handle these cases, but no concrete implementation ideas
right now.

[TNS-38]: http://dev.clojure.org/jira/browse/TNS-38
[deps-from-ns-decl]: https://github.com/clojure/tools.namespace/blob/b9de9386d37e0de9660718b426c06b8671560944/src/main/clojure/clojure/tools/namespace/parse.cljc#L123
[add-files]: https://github.com/clojure/tools.namespace/blob/b9de9386d37e0de9660718b426c06b8671560944/src/main/clojure/clojure/tools/namespace/file.clj#L76

**Comment by benedekfazekas** [comment] 2015-11-28 13:03
@expez care to pop into the gitter room wrt this issue?

**Comment by expez** [comment] 2015-12-14 13:13
Rum is also affected by this: https://github.com/tonsky/rum/issues/54

**Comment by benedekfazekas** [comment] 2015-12-14 13:25
what about going with the temporary fix @expez?

**Comment by expez** [comment] 2015-12-14 13:29
> what about going with the temporary fix @expez?

I still don't think that's a good idea. 

I'll have time to write our own tracker early next year, unless this is solved upstream by then.

**Comment by benedekfazekas** [comment] 2015-12-14 13:31
okay. does this blocks 2.0 tho?

**Comment by expez** [comment] 2015-12-14 13:34
> okay. does this blocks 2.0 tho?

No, I don't think that's warranted.  Fixing this won't create any API incompatibilities.  Moving from the tools.namespace tracker to our own tracker is just an internal change.

**Comment by benedekfazekas** [comment] 2015-12-14 13:40
fair point wrt API change. on the other hand it completely blocks users to use refactor-nrepl if they use certain deps in their project. but I appreciate that you don't wanna go with the temporary fix.

**Comment by benedekfazekas** [comment] 2015-12-14 13:41
will try to have a look on the TNS issue

**Comment by magnars** [comment] 2015-12-14 13:41
It blocks most of my usage, as one example.

**Comment by benedekfazekas** [comment] 2015-12-14 14:09
any ways we could perhaps enhance the temporary fix (crazy things like warn when `rename-file` is used or completely disable it for projects where we detect multiple platform namespaces (we can figure this out without the tracker i guess)) again, I appreciate that you don't wanna go with a temp fix which actually breaks a feature really badly but on the other hand this is a serious blocker for many users.

**Comment by expez** [comment] 2015-12-14 14:24
First priority now is getting 2.0.0 out the door so people don't have to depend on snapshots anymore.

 Once that is done I'll tackle this.  That means any temporary fix will only have a lifetime of around 2-3 weeks.  Furthermore, the lifetime of the temp-fix overlaps with the holiday when people are doing less refactoring than usual.

There's also the issue of teaching people about the tempfix (double prefix means force? new setting?).  Most likely a permanent solution is out by the time people have 1) decided to upgrade 2) learned about the workaround. 

Since people haven't been bumping this thread with "+1" at all, I'm also thinking this doesn't affect a lot of users, yet.

**Comment by bilus** [comment] 2015-12-31 19:04
+1

**Comment by expez** [comment] 2016-01-02 17:01
@stuartsierra Any plans on solving this in the immediate future (say in the next 2-3 weeks)?  I started working on a file-based tracker (instead of a namespace based one), but I'd obviously love to offload this work to TNS :)

**Comment by benedekfazekas** [comment] 2016-01-05 14:12
@expez: @stuartsierra just pushed a fix for TNS-38 along the lines of his previous commit. Are you happy with go with this (at least temporarily) as soon as an alpha is released?

**Comment by magnars** [comment] 2016-01-05 15:18
The fix for TNS-38 looks good to me at least. And I'd be thrilled to use clj-refactor again too.

**Comment by stuartsierra** [comment] 2016-01-05 20:42
Just released [tools.namespace 0.3.0-alpha3](https://groups.google.com/d/topic/clojure/iGFIQi9L-8Q/discussion).

This contains the [TNS-38](http://dev.clojure.org/jira/browse/TNS-38) fix described [above](https://github.com/clojure-emacs/refactor-nrepl/issues/127#issuecomment-156540140),
which ignores `:require-macros` and `:use-macros` completely. This
effectively isolates the dependency graph for each "platform"
(Clojure or ClojureScript).

**Comment by benedekfazekas** [comment] 2016-01-05 22:59
upgraded TNS dependency and released new snapshot to clojars.

@magnars @bilus pls test if you are ok with latest snapshot.

I keep the issue open because as expected cljs->clj (via `:require-macros`) is not tracked so this is a temporary fix with some regression for now.

**Comment by magnars** [comment] 2016-01-06 07:39
@benedekfazekas Thanks! :smile: Would that be `2.0.0-SNAPSHOT` or `2.1.0-alpha1`?

**Comment by benedekfazekas** [comment] 2016-01-06 07:43
the snapshot

**Comment by magnars** [comment] 2016-01-06 09:04
@benedekfazekas That solved the issue for me. It was nice seeing the find-usages window again. :sunglasses:

**Comment by benedekfazekas** [comment] 2016-01-06 09:17
Nice one! :)

**Comment by magnars** [comment] 2016-02-21 16:58
Time to close this?

**Comment by benedekfazekas** [comment] 2016-02-21 20:06
yup, I think. there is a branch by @expez with a more ambitious solution with a new tracker in the works so that won't go forgotten.

**Closed by benedekfazekas** 2016-02-21 20:06 UTC
