### ISSUE TITLE
clean-ns: false positives for functions called exclusively inside metadata

### ISSUE THREAD

**Issue by vemv** [clojure-emacs/refactor-nrepl#240] opened 2019-02-05 06:38 UTC
Similar to #239. Here what gets wiped is function calls contained inside metadata:

```
(ns f.oo
  (:require [foo.util :as util]))

(def ^{:x (util/bar)} x 3)
```

...for the code above, `clean-ns` will remove the the require.

**Comment by expez** [comment] 2019-02-05 11:03
I'm closing this as a duplicate of https://github.com/clojure-emacs/refactor-nrepl/issues/239, because solving that one will also solve this one.

Thanks for the report! :+1:

**Closed by expez** 2019-02-05 11:03 UTC
